# -*- coding: utf-8 -*-
"""EMRapp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1heSUoU4vHj-YsmhLaTvLWGRf0ZnWwlZy
"""

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import pandas as pd
import datetime

# Load artifacts
model = joblib.load('no_show_model.pkl')
ne_map = joblib.load('neighborhood_encoder.pkl')

app = FastAPI()

class Appointment(BaseModel):
    PatientId: str
    AppointmentDay: datetime.datetime
    ScheduledDay: datetime.datetime
    Age: int
    Gender: str
    Neighbourhood: str
    Scholarship: bool
    Hipertension: bool
    Diabetes: bool
    Alcoholism: bool
    Handcap: bool
    SMS_received: bool
    Date_diff: int

@app.post("/predict_no_show")
def predict(appt: Appointment):
    # Inline feature engineering
    lead = appt.Date_diff
    lt = pd.cut(
        [lead],
        bins=[-1, 0, 7, 14, 30, lead],
        labels=['Same Day','1–7 days','8–14 days','15–30 days','>30 days']
    )[0]
    weekday = appt.AppointmentDay.day_name()
    month   = appt.AppointmentDay.month
    neigh_te = ne_map.get(appt.Neighbourhood, df['Showed_up'].mean())

    features = [
        appt.Age,
        int(appt.Scholarship), int(appt.Hipertension), int(appt.Diabetes),
        int(appt.Alcoholism), int(appt.Handcap), int(appt.SMS_received),
        ['Same Day','1–7 days','8–14 days','15–30 days','>30 days'].index(lt),
        ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].index(weekday),
        month,
        1 if appt.Gender=='M' else 0,
        neigh_te
    ]

    prob = model.predict_proba([features])[0][1]
    return {"no_show_probability": round(float(prob), 4)}